In [46]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [47]:
from sklearn.datasets import load_diabetes

In [48]:
dataset=load_diabetes()

In [49]:
dataset.feature_names

['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']

In [50]:
dataset.target

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 288.,  88., 292.,  71.,
       197., 186.,  25.,  84.,  96., 195.,  53., 217., 172., 131., 214.,
        59.,  70., 220., 268., 152.,  47.,  74., 295., 101., 151., 127.,
       237., 225.,  81., 151., 107.,  64., 138., 185., 265., 101., 137.,
       143., 141.,  79., 292., 178.,  91., 116.,  86., 122.,  72., 129.,
       142.,  90., 158.,  39., 196., 222., 277.,  99., 196., 202., 155.,
        77., 191.,  70.,  73.,  49.,  65., 263., 248., 296., 214., 185.,
        78.,  93., 252., 150.,  77., 208.,  77., 108., 160.,  53., 220.,
       154., 259.,  90., 246., 124.,  67.,  72., 257., 262., 275., 177.,
        71.,  47., 187., 125.,  78.,  51., 258., 215., 303., 243.,  91.,
       150., 310., 153., 346.,  63.,  89.,  50.,  39., 103., 308., 116.,
       145.,  74.,  45., 115., 264.,  87., 202., 127., 182., 241.,  66.,
        94., 283.,  64., 102., 200., 265.,  94., 230., 181., 156., 233.,
        60., 219.,  80.,  68., 332., 248.,  84., 200.,  55.,  85.,  89.,
        31., 129.,  83., 275.,  65., 198., 236., 253., 124.,  44., 172.,
       114., 142., 109., 180., 144., 163., 147.,  97., 220., 190., 109.,
       191., 122., 230., 242., 248., 249., 192., 131., 237.,  78., 135.,
       244., 199., 270., 164.,  72.,  96., 306.,  91., 214.,  95., 216.,
       263., 178., 113., 200., 139., 139.,  88., 148.,  88., 243.,  71.,
        77., 109., 272.,  60.,  54., 221.,  90., 311., 281., 182., 321.,
        58., 262., 206., 233., 242., 123., 167.,  63., 197.,  71., 168.,
       140., 217., 121., 235., 245.,  40.,  52., 104., 132.,  88.,  69.,
       219.,  72., 201., 110.,  51., 277.,  63., 118.,  69., 273., 258.,
        43., 198., 242., 232., 175.,  93., 168., 275., 293., 281.,  72.,
       140., 189., 181., 209., 136., 261., 113., 131., 174., 257.,  55.,
        84.,  42., 146., 212., 233.,  91., 111., 152., 120.,  67., 310.,
        94., 183.,  66., 173.,  72.,  49.,  64.,  48., 178., 104., 132.,
       220.,  57.])

In [51]:
df=pd.DataFrame(dataset.data,columns=['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5','s6'])

In [52]:
df

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641
...,...,...,...,...,...,...,...,...,...,...
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064

In [53]:
from sklearn.model_selection import train_test_split

In [54]:
X=df.iloc[:,:-1]
Y=dataset['target']

In [55]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.33,random_state=42)

In [58]:
X_train.corr()

,age,sex,bmi,bp,s1,s2,s3,s4,s5
age,1.000000,0.158365,0.154118,0.296175,0.256847,0.199423,-0.027358,0.167114,0.265242
sex,0.158365,1.000000,0.064689,0.179566,0.039423,0.134719,-0.350479,0.339617,0.129306
bmi,0.154118,0.064689,1.000000,0.377067,0.237922,0.255167,-0.378082,0.434438,0.439079
bp,0.296175,0.179566,0.377067,1.000000,0.239817,0.165235,-0.110201,0.212675,0.353409
s1,0.256847,0.039423,0.237922,0.239817,1.000000,0.887722,0.060949,0.547016,0.522204
s2,0.199423,0.134719,0.255167,0.165235,0.887722,1.000000,-0.181797,0.646648,0.294901
s3,-0.027358,-0.350479,-0.378082,-0.110201,0.060949,-0.181797,1.000000,-0.729197,-0.373460
s4,0.167114,0.339617,0.434438,0.212675,0.547016,0.646648,-0.729197,1.000000,0.619194
s5,0.265242,0.129306,0.439079,0.353409,0.522204,0.294901,-0.373460,0.619194,1.000000

In [59]:
from sklearn.tree import DecisionTreeRegressor

In [ ]:
Tree=DecisionTreeRegressor()

In [61]:
Tree.fit(X_train,Y_train)

DecisionTreeRegressor()

In [62]:
y_pred=Tree.predict(X_test)

In [63]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [73]:
mse=mean_squared_error(y_pred,Y_test)
mae=mean_absolute_error(y_pred,Y_test)
rmse=np.sqrt(mse)
r2=r2_score(y_pred,Y_test)
print(mse)
print(mae)
print(rmse)
print(r2)

6781.945205479452
65.01369863013699
82.35256647779383
-0.16333846885722614

In [74]:
Param={'criterion':['squared_error', 'friedman_mse', 'absolute_error', 'poisson'],
       'splitter':['best', 'random'],'max_depth':[1,2,3,4,5,6,7,8,9,10]}

In [75]:
from sklearn.model_selection import GridSearchCV

In [82]:
Grid=GridSearchCV(Tree,param_grid=Param,scoring='r2')

In [83]:
Grid.fit(X_train,Y_train)

GridSearchCV(estimator=DecisionTreeRegressor(),
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_depth': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                         'splitter': ['best', 'random']},
             scoring='r2')

In [84]:
Grid.best_params_

{'criterion': 'friedman_mse', 'max_depth': 3, 'splitter': 'best'}

In [85]:
Grid.best_score_

np.float64(0.34936698909416475)

In [86]:
Grid.best_estimator_

DecisionTreeRegressor(criterion='friedman_mse', max_depth=3)