In [62]:
import tensorflow as tf
from tensorflow.keras.models import load_model
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime
import pandas as pd
import numpy as np
import pickle

In [63]:
# load the ANN model
model = load_model('model.h5')

# load the encoders & scaler
with open('label_encoder_gender.pkl', 'rb') as file:
    label_encoder_gender = pickle.load(file)

with open('Geography_Encoder.pkl', 'rb') as file:
    Geography_Encoder = pickle.load(file)

with open('Scaler.pkl', 'rb') as file:
    scaler = pickle.load(file)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [64]:
input_data={
    'CreditScore':600,
    'Geography':'France',
    'Gender':'Male',
    'Age':40,
    'Tenure':3,
    'Balance':60000,
    'NumOfProducts':2,
    'HasCrCard':1,
    'IsActiveMember':1,
    'EstimatedSalary':50000

}

In [65]:
# One-hot encode 'Geography'
geo_encoded = Geography_Encoder.transform([[input_data['Geography']]])
geo_encoded_df = pd.DataFrame(geo_encoded, columns=Geography_Encoder.get_feature_names_out(['Geography']))
geo_encoded_df

c:\Users\Aryan Chauhan\anaconda3\envs\geoai\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [66]:
input_data_df=pd.DataFrame([input_data])

In [67]:
input_data=pd.concat([input_data_df,geo_encoded_df],axis=1)

In [68]:
input_data.drop(columns=['Geography'],inplace=True)

In [69]:
input_data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,Male,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [70]:
#Encode
input_data['Gender']=label_encoder_gender.transform(input_data['Gender'])

In [71]:
input_data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [72]:
## Scaling the input data
input_scaled=scaler.transform(input_data)

In [73]:
prediction=model.predict(input_scaled)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 256ms/step

array([[0.06357532]], dtype=float32)

In [ ]:
prediction_proba = prediction[0][0]
prediction_proba

np.float32(0.06357532)

In [75]:
if prediction_proba > 0.5:
    print('The customer is likely to churn.')
else:
    print('The customer is not likely to churn.')

The customer is not likely to churn.