In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder,LabelEncoder
import pickle

In [2]:
df=pd.read_csv("Churn_Modelling.csv")

In [3]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
#Preprocessing the data
df=df.drop(columns=['RowNumber','CustomerId','Surname'])

In [5]:
Scaler=StandardScaler()
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [6]:
df['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [7]:
df['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [8]:
label_encoder_gender=LabelEncoder()
df['Gender']=label_encoder_gender.fit_transform(df['Gender'])

In [9]:
from sklearn.preprocessing import OneHotEncoder

In [10]:
Geography_Encoder=OneHotEncoder(sparse_output=False)
geo_encoded=Geography_Encoder.fit_transform(df[['Geography']])

In [11]:
Geography_Encoder.get_feature_names_out()

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [12]:
geo_encoded_df=pd.DataFrame(geo_encoded,columns=Geography_Encoder.get_feature_names_out())

In [13]:
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [14]:
df=pd.concat([df.drop('Geography',axis=1),geo_encoded_df],axis=1)

In [15]:
df.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [16]:
with open ('Geography_Encoder.pkl','wb') as file:
    pickle.dump(Geography_Encoder,file)
with open ('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)
with open('Scaler.pkl','wb') as file:
    pickle.dump(Scaler,file)

In [17]:
X=df.drop(columns=['EstimatedSalary'])
Y=df['EstimatedSalary']

In [18]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.20,random_state=42)

In [20]:
X_train=Scaler.fit_transform(X_train)
X_test=Scaler.transform(X_test)

In [25]:
#ANN
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [27]:
model = Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1)#OutputLayer
]

)

In [30]:
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

In [32]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [34]:
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [35]:
log_dir="regressionlogs/fit/"
tensorboard_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [38]:
early_stopping=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [39]:
history=model.fit(
    X_train,Y_train,
    validation_data=(X_test,Y_test),
    epochs=100,
    callbacks=[early_stopping,tensorboard_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 100361.8438 - mae: 100361.8438 - val_loss: 98462.5547 - val_mae: 98462.5547
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 99441.9219 - mae: 99441.9219 - val_loss: 96615.3047 - val_mae: 96615.3047
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 96267.2500 - mae: 96267.2500 - val_loss: 91975.6328 - val_mae: 91975.6328
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 90158.0469 - mae: 90158.0469 - val_loss: 84498.6797 - val_mae: 84498.6797
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 81492.8906 - mae: 81492.8906 - val_loss: 75116.0781 - val_mae: 75116.0781
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 71731.7656 - mae: 71731.7656 - val_loss: 66052.0547 - val_mae: 66052.0547
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 63023.6797 - mae: 63023.6797 - val_loss: 58880.6133 - val_mae: 58880.6133
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 56783.5000 - mae: 56783.5000 - val_loss: 54245.4688 - val_mae: 54245.4688
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 53179.6133 - mae: 53179.6133 - val_loss: 52067.7383 - val_mae: 52067.7383
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - loss: 51471.7852 - mae: 51471.7852 - val_loss: 51224.4062 - val_mae: 51224.4062
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 50749.9688 - mae: 50749.9688 - val_loss: 50938.9531 - val_mae: 50938.9531
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 50462.4844 - mae: 50462.4844 - val_loss: 50798.2852 - val_mae: 50798.2852
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50327.4766 - mae: 50327.4766 - val_loss: 50710.7617 - val_mae: 50710.7617
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50237.2344 - mae: 50237.2344 - val_loss: 50654.3555 - val_mae: 50654.3555
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50173.3945 - mae: 50173.3945 - val_loss: 50600.9023 - val_mae: 50600.9023
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50115.5234 - mae: 50115.5234 - val_loss: 50555.6797 - val_mae: 50555.6797
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50068.6953 - mae: 50068.6953 - val_loss: 50529.9609 - val_mae: 50529.9609
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50026.5273 - mae: 50026.5273 - val_loss: 50486.1875 - val_mae: 50486.1875
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49992.0547 - mae: 49992.0547 - val_loss: 50470.2305 - val_mae: 50470.2305
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49955.9453 - mae: 49955.9453 - val_loss: 50455.3086 - val_mae: 50455.3086
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49924.2305 - mae: 49924.2305 - val_loss: 50439.4922 - val_mae: 50439.4922
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49897.3203 - mae: 49897.3203 - val_loss: 50417.7031 - val_mae: 50417.7031
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49870.6367 - mae: 49870.6367 - val_loss: 50388.4688 - val_mae: 50388.4688
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49843.9414 - mae: 49843.9414 - val_loss: 50385.2734 - val_mae: 50385.2734
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49822.7969 - mae: 49822.7969 - val_loss: 50362.8984 - val_mae: 50362.8984
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49800.7344 - mae: 49800.7344 - val_loss: 50352.8711 - val_mae: 50352.8711
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49778.6602 - mae: 49778.6602 - val_loss: 50342.7969 - val_mae: 50342.7969
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49760.3828 - mae: 49760.3828 - val_loss: 50331.1523 - val_mae: 50331.1523
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49741.9961 - mae: 49741.9961 - val_loss: 50325.2461 - val_mae: 50325.2461
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49725.4883 - mae: 49725.4883 - val_loss: 50310.6914 - val_mae: 50310.6914
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49710.0664 - mae: 49710.0664 - val_loss: 50304.9219 - val_mae: 50304.9219
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49693.8594 - mae: 49693.8594 - val_loss: 50305.5586 - val_mae: 50305.5586
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49678.8633 - mae: 49678.8633 - val_loss: 50280.3359 - val_mae: 50280.3359
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49663.8281 - mae: 49663.8281 - val_loss: 50268.6914 - val_mae: 50268.6914
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49651.0078 - mae: 49651.0078 - val_loss: 50261.9531 - val_mae: 50261.9531
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49636.1445 - mae: 49636.1445 - val_loss: 50279.4609 - val_mae: 50279.4609
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49625.8555 - mae: 49625.8555 - val_loss: 50265.9414 - val_mae: 50265.9414
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49616.6055 - mae: 49616.6055 - val_loss: 50264.6055 - val_mae: 50264.6055
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49602.9648 - mae: 49602.9648 - val_loss: 50258.3008 - val_mae: 50258.3008
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49592.2695 - mae: 49592.2695 - val_loss: 50264.1133 - val_mae: 50264.1133
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49579.2891 - mae: 49579.2891 - val_loss: 50260.8008 - val_mae: 50260.8008
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49574.4688 - mae: 49574.4688 - val_loss: 50256.2930 - val_mae: 50256.2930
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49565.1328 - mae: 49565.1328 - val_loss: 50255.8867 - val_mae: 50255.8867
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49552.5391 - mae: 49552.5391 - val_loss: 50261.8477 - val_mae: 50261.8477
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49543.2656 - mae: 49543.2656 - val_loss: 50254.4805 - val_mae: 50254.4805
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49535.9922 - mae: 49535.9922 - val_loss: 50239.5547 - val_mae: 50239.5547
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49524.9258 - mae: 49524.9258 - val_loss: 50242.0859 - val_mae: 50242.0859
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49519.3594 - mae: 49519.3594 - val_loss: 50244.3711 - val_mae: 50244.3711
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49511.0938 - mae: 49511.0938 - val_loss: 50234.9648 - val_mae: 50234.9648
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49507.4883 - mae: 49507.4883 - val_loss: 50246.9609 - val_mae: 50246.9609
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49494.7109 - mae: 49494.7109 - val_loss: 50230.2227 - val_mae: 50230.2227
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49489.4336 - mae: 49489.4336 - val_loss: 50252.0312 - val_mae: 50252.0312
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49485.9648 - mae: 49485.9648 - val_loss: 50258.4609 - val_mae: 50258.4609
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49477.5000 - mae: 49477.5000 - val_loss: 50251.7031 - val_mae: 50251.7031
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49471.8711 - mae: 49471.8711 - val_loss: 50257.2344 - val_mae: 50257.2344
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49465.6172 - mae: 49465.6172 - val_loss: 50252.1484 - val_mae: 50252.1484
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 49457.9023 - mae: 49457.9023 - val_loss: 50266.3281 - val_mae: 50266.3281
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49451.7969 - mae: 49451.7969 - val_loss: 50258.7070 - val_mae: 50258.7070
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49447.9414 - mae: 49447.9414 - val_loss: 50268.8867 - val_mae: 50268.8867
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49443.7773 - mae: 49443.7773 - val_loss: 50273.3867 - val_mae: 50273.3867
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49433.5898 - mae: 49433.5898 - val_loss: 50251.3945 - val_mae: 50251.3945

In [40]:
%load_ext tensorboard

In [45]:
%tensorboard --log_dir regressionlogs/fit

ERROR: Failed to launch TensorBoard (exited with 1).
Contents of stderr:
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1788790998.842010   22656 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1788791002.693539   22656 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
Error: A logdir or db must be specified. For example `tensorboard --logdir mylogdir` or `tensorboard --db sqlite:~/.tensorboard.db`. Run `tensorboard --helpfull` for details and examples.

In [46]:
test_loss,test_mae=model.evaluate(X_test,Y_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50230.2227 - mae: 50230.2227

In [47]:
print(test_loss)
print(test_mae)

50230.22265625
50230.22265625

In [48]:
model.save('regression.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.