In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("Algerian_forest_fires_dataset_UPDATE.csv",header=1)
df

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
0,01,06,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4,0.5,not fire
1,02,06,2012,29,61,13,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire
2,03,06,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire
3,04,06,2012,25,89,13,2.5,28.6,1.3,6.9,0,1.7,0,not fire
4,05,06,2012,27,77,16,0,64.8,3,14.2,1.2,3.9,0.5,not fire
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
241,26,09,2012,30,65,14,0,85.4,16,44.5,4.5,16.9,6.5,fire
242,27,09,2012,28,87,15,4.4,41.1,6.5,8,0.1,6.2,0,not fire
243,28,09,2012,27,87,29,0.5,45.9,3.5,7.9,0.4,3.4,0.2,not fire
244,29,09,2012,24,54,18,0.1,79.7,4.3,15.2,1.7,5.1,0.7,not fire
245,30,09,2012,24,64,15,0.2,67.3,3.8,16.5,1.2,4.8,0.5,not fire

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 246 entries, 0 to 245
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          246 non-null    str
 1   month        245 non-null    str
 2   year         245 non-null    str
 3   Temperature  245 non-null    str
 4    RH          245 non-null    str
 5    Ws          245 non-null    str
 6   Rain         245 non-null    str
 7   FFMC         245 non-null    str
 8   DMC          245 non-null    str
 9   DC           245 non-null    str
 10  ISI          245 non-null    str
 11  BUI          245 non-null    str
 12  FWI          245 non-null    str
 13  Classes      244 non-null    str
dtypes: str(14)
memory usage: 27.0 KB

In [4]:
df.columns = df.columns.str.strip()

In [5]:
df["day"]=pd.to_numeric(df["day"],errors="coerce")

In [6]:
df["month"]=pd.to_numeric(df["month"],errors="coerce")

In [7]:
df["year"]=pd.to_numeric(df["year"],errors="coerce")

In [8]:
df["Temperature"]=pd.to_numeric(df["Temperature"],errors="coerce")

In [9]:
df["RH"]=pd.to_numeric(df["RH"],errors="coerce")

In [10]:
df["Ws"]=pd.to_numeric(df["Ws"],errors="coerce")

In [11]:
df["Rain"]=pd.to_numeric(df["Rain"],errors="coerce")

In [12]:
df["FFMC"]=pd.to_numeric(df["FFMC"],errors="coerce")

In [13]:
df["DMC"]=pd.to_numeric(df["DC"],errors="coerce")

In [14]:
df["ISI"]=pd.to_numeric(df["ISI"],errors="coerce")

In [15]:
df["BUI"]=pd.to_numeric(df["BUI"],errors="coerce")

In [16]:
df["FWI"]=pd.to_numeric(df["FWI"],errors="coerce")

In [17]:
df["DC"]=pd.to_numeric(df["DC"],errors="coerce")

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 246 entries, 0 to 245
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          244 non-null    float64
 1   month        244 non-null    float64
 2   year         244 non-null    float64
 3   Temperature  244 non-null    float64
 4   RH           244 non-null    float64
 5   Ws           244 non-null    float64
 6   Rain         244 non-null    float64
 7   FFMC         244 non-null    float64
 8   DMC          243 non-null    float64
 9   DC           243 non-null    float64
 10  ISI          244 non-null    float64
 11  BUI          244 non-null    float64
 12  FWI          243 non-null    float64
 13  Classes      244 non-null    str
dtypes: float64(13), str(1)
memory usage: 27.0 KB

In [19]:
df[df.isnull().any(axis=1)]

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
122,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
123,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Classes
167,14.0,7.0,2012.0,37.0,37.0,18.0,0.2,88.9,NaN,NaN,12.5,10.4,NaN,NaN

In [20]:
df.loc[:122,"Region"]=0
df.loc[122:,"Region"]=1

In [21]:
df.isnull().sum()

day            2
month          2
year           2
Temperature    2
RH             2
Ws             2
Rain           2
FFMC           2
DMC            3
DC             3
ISI            2
BUI            2
FWI            3
Classes        2
Region         0
dtype: int64

In [22]:
df=df.dropna().reset_index(drop=True)

In [23]:
df.isnull().sum()

day            0
month          0
year           0
Temperature    0
RH             0
Ws             0
Rain           0
FFMC           0
DMC            0
DC             0
ISI            0
BUI            0
FWI            0
Classes        0
Region         0
dtype: int64

In [24]:
df.iloc[[122]]

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes,Region
122,1.0,6.0,2012.0,32.0,71.0,12.0,0.7,57.1,8.2,8.2,0.6,2.8,0.2,not fire,1.0

In [25]:
df.columns

Index(['day', 'month', 'year', 'Temperature', 'RH', 'Ws', 'Rain', 'FFMC',
       'DMC', 'DC', 'ISI', 'BUI', 'FWI', 'Classes', 'Region'],
      dtype='str')

In [26]:
#df[['day', 'month', 'year', 'Temperature', 'RH', 'Ws', 'Rain', 'FFMC','DMC', 'DC', 'ISI', 'BUI', 'FWI']]=df[['day', 'month', 'year', 'Temperature', 'RH', 'Ws', 'Rain', 'FFMC','DMC', 'DC', 'ISI', 'BUI', 'FWI']].astype(int)

In [27]:
df.describe()

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Region
count,243.000000,243.000000,243.0,243.000000,243.000000,243.000000,243.000000,243.000000,243.000000,243.000000,243.000000,243.000000,243.000000,243.000000
mean,15.761317,7.502058,2012.0,32.152263,62.041152,15.493827,0.762963,77.842387,49.430864,49.430864,4.742387,16.690535,7.035391,0.497942
std,8.842552,1.114793,0.0,3.628039,14.828160,2.811385,2.003207,14.349641,47.665606,47.665606,4.154234,14.228421,7.440568,0.501028
min,1.000000,6.000000,2012.0,22.000000,21.000000,6.000000,0.000000,28.600000,6.900000,6.900000,0.000000,1.100000,0.000000,0.000000
25%,8.000000,7.000000,2012.0,30.000000,52.500000,14.000000,0.000000,71.850000,12.350000,12.350000,1.400000,6.000000,0.700000,0.000000
50%,16.000000,8.000000,2012.0,32.000000,63.000000,15.000000,0.000000,83.300000,33.100000,33.100000,3.500000,12.400000,4.200000,0.000000
75%,23.000000,8.000000,2012.0,35.000000,73.500000,17.000000,0.500000,88.300000,69.100000,69.100000,7.250000,22.650000,11.450000,1.000000
max,31.000000,9.000000,2012.0,42.000000,90.000000,29.000000,16.800000,96.000000,220.400000,220.400000,19.000000,68.000000,31.100000,1.000000

In [28]:
df.corr

<bound method DataFrame.corr of       day  month    year  Temperature    RH    Ws  Rain  FFMC   DMC    DC  \
0     1.0    6.0  2012.0         29.0  57.0  18.0   0.0  65.7   7.6   7.6
1     2.0    6.0  2012.0         29.0  61.0  13.0   1.3  64.4   7.6   7.6
2     3.0    6.0  2012.0         26.0  82.0  22.0  13.1  47.1   7.1   7.1
3     4.0    6.0  2012.0         25.0  89.0  13.0   2.5  28.6   6.9   6.9
4     5.0    6.0  2012.0         27.0  77.0  16.0   0.0  64.8  14.2  14.2
..    ...    ...     ...          ...   ...   ...   ...   ...   ...   ...
238  26.0    9.0  2012.0         30.0  65.0  14.0   0.0  85.4  44.5  44.5
239  27.0    9.0  2012.0         28.0  87.0  15.0   4.4  41.1   8.0   8.0
240  28.0    9.0  2012.0         27.0  87.0  29.0   0.5  45.9   7.9   7.9
241  29.0    9.0  2012.0         24.0  54.0  18.0   0.1  79.7  15.2  15.2
242  30.0    9.0  2012.0         24.0  64.0  15.0   0.2  67.3  16.5  16.5

     ISI   BUI  FWI       Classes  Region
0    1.3   3.4  0.5   not fire        0.0
1    1.0   3.9  0.4   not fire        0.0
2    0.3   2.7  0.1   not fire        0.0
3    0.0   1.7  0.0   not fire        0.0
4    1.2   3.9  0.5   not fire        0.0
..   ...   ...  ...           ...     ...
238  4.5  16.9  6.5       fire        1.0
239  0.1   6.2  0.0   not fire        1.0
240  0.4   3.4  0.2   not fire        1.0
241  1.7   5.1  0.7   not fire        1.0
242  1.2   4.8  0.5  not fire         1.0

[243 rows x 15 columns]>

In [29]:
df.to_csv("Algerian Fire Clean.csv",index=False)